favicon:
  desktop:
    url: /images/favicon.ico
    gravatar: false
  android:
    url: /images/favicon-192x192.png
    gravatar: false
  apple:
    url: /images/apple-touch-icon.png
    gravatar: false

logo:
  enabled: true
  width: 50
  height: 50
  url: /images/logo.png
  gravatar: false
  grayout: true

nav:
  home: /
  articles: /archives/
  search: /search/
  travelling: https://travellings.now.sh

social_links:
  github: http://github.com/{{github_username}}

colorscheme: "dark"
